name: Compile Kernel

on:
  workflow_dispatch:
    inputs:
      device:
        description: 'Select an option'
        required: true
        type: choice
        options:
          - starlte
          - starltekor
          - star2lte
          - star2ltekor
          - crownlte
          - crownltekor
          - build all/zip
          - abort

jobs:
  run-apollo-script:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the branch that triggered the workflow
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      # Determine the input value to send to the script
      - name: Set input value
        id: set_input
        run: |
          case "${{ github.event.inputs.device }}" in
            starlte) echo "INPUT_VALUE=1" >> $GITHUB_ENV ;;
            starltekor) echo "INPUT_VALUE=4" >> $GITHUB_ENV ;;
            star2lte) echo "INPUT_VALUE=2" >> $GITHUB_ENV ;;
            star2ltekor) echo "INPUT_VALUE=5" >> $GITHUB_ENV ;;
            crownlte) echo "INPUT_VALUE=3" >> $GITHUB_ENV ;;
            crownltekor) echo "INPUT_VALUE=6" >> $GITHUB_ENV ;;
            "build all/zip") echo "INPUT_VALUE=7" >> $GITHUB_ENV ;;
            abort) echo "INPUT_VALUE=8" >> $GITHUB_ENV ;;
          esac

      # Run the apollo.sh script with the selected input
      - name: Run apollo.sh script with input
        run: |
          echo "${INPUT_VALUE}" | ./apollo.sh
